# permissions for end users to view kubenchmarks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubenchmark-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubenchmark-viewer-role
rules:
- apiGroups:
  - testing.testing.com
  resources:
  - kubenchmarks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testing.testing.com
  resources:
  - kubenchmarks/status
  verbs:
  - get
